export const teamName = {
  1: "Baltimore Orioles",
  2: "Boston Red Sox",
  3: "Los Angeles Angels",
  4: "Chicago White Sox",
  5: "Cleveland Guardians",
  6: "Detroit Tigers",
  7: "Kansas City Royals",
  8: "Milwaukee Brewers",
  9: "Minnesota Twins",
  10: "New York Yankees",
  11: "Oakland Athletics",
  12: "Seattle Mariners",
  13: "Texas Rangers",
  14: "Toronto Blue Jays",
  15: "Atlanta Braves",
  16: "Chicago Cubs",
  17: "Cincinnati Reds",
  18: "Houston Astros",
  19: "Los Angeles Dodgers",
  20: "Washington Nationals",
  21: "New York Mets",
  22: "Philadelphia Phillies",
  23: "Pittsburgh Pirates",
  24: "St. Louis Cardinals",
  25: "San Diego Padres",
  26: "San Francisco Giants",
  27: "Colorado Rockies",
  28: "Miami Marlins",
  29: "Arizona Diamondbacks",
  30: "Tampa Bay Rays"
};
